sowp_budget_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

sowp_budget_admin_category:
    resource: "@SowpBudgetBundle/Controller/AdminCategoryController.php"
    type:     annotation
    prefix: /admin

sowp_budget_category:
    resource: "@SowpBudgetBundle/Controller/BudgetController.php"
    type:     annotation
    prefix: /budget

sowp_budget_api:
    resource: "@SowpBudgetBundle/Resources/config/routing_api.yml"
    type:     rest
    prefix: api
    defaults:
      _format: "json"

