<?php

namespace Sowp\BudgetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractRepository extends EntityRepository
{
    use findAllQueryTrait;

    public function getContractsWithCategoryQuery()
    {
        return $this->_em->createQuery(<<<DQL
        SELECT 
            a, 
            cat 
        FROM 
            Sowp\BudgetBundle\Entity\Contract a JOIN a.category cat
DQL
        );
    }

    public function getContractsWithCategory()
    {
        return $this->getContractsWithCategoryQuery()->getResult();
    }
}
