<?php

namespace Sowp\BudgetBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Sowp\BudgetBundle\Entity\Category;
use Sowp\BudgetBundle\Entity\Contract;

/**
 * ContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractRepository extends EntityRepository
{
    use findAllQueryTrait;

    public function getContractsWithCategoryQuery() { 
        return $this->_em->createQuery("SELECT c, cat FROM Sowp\BudgetBundle\Entity\Contract c JOIN c.category cat");
    }

    public function getContractsWithCategory() { 
        return $this->getContractsWithCategoryQuery()->getResult();
    }

    public function getContractsInCategory(Category $category) {
        return $this->getEntityManager()->createQuery("
            SELECT 
                c 
            FROM 
                SowpBudgetBundle:Contract c,
                SowpBudgetBundle:Category node,
                SowpBudgetBundle:Category parent 
            WHERE 
                c.category = node.id AND
                node.lft BETWEEN parent.lft AND parent.rgt
                    AND parent.id = ?1
                    AND node.root = ?2")
        ->setParameter(1, $category->getId())
        ->setParameter(2, $category->getRoot()->getId());
    }
}
